definitions:
  Error:
    title: Error
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  ServerError:
    allOf:
      - $ref: '#/definitions/Error'
      - title: ServerError
  NotFoundError:
    allOf:
      - $ref: '#/definitions/Error'
      - title: NotFoundError
  ValidationError:
    allOf:
      - $ref: '#/definitions/Error'
      - title: ValidationError
      - properties:
          details:
            type: array
            items:
              title: FieldError
              type: object
              properties:
                message:
                  type: string
                param:
                  type: string
  App:
    title: App
    type: object
    properties:
      app:
        type: string
      appVersion:
        type: string

/:
  get:
    summary: Get API version
    description: App version
    produces:
      - application/json
    tags:
      - Base
    responses:
      200:
        description: Application and API version
        schema:
          title: App
          type: object
          $ref: '#/definitions/App'
