version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app/
    ports:
      - "8088:8088"
    command: yarn start:dev
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web
